---
engines:
  pmd: 
    enabled: true
  sonar-java:
    enabled: false
    config:
      minimum_severity: info
      sonar.java.source: 8
      tests_patterns:
        - src/test/**
exclude_paths:
- .devops/
